[build]
    functions = "functions"

[[redirects]]
    from = "/api/*"
    to = "https://graphql.fauna.com/graphql"
    status = 200
    force = true
    headers = { Authorization = "Bearer HEADER_PLACEHOLDER" }