[build]
    functions = "functions"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/contact"
  status = 200
  force = true
  headers = {authorization = "Bearer HEADER_PLACEHOLDER"}
  token = "HEADER_PLACEHOLDER"