[build]
    functions = "functions"
    environment = {FAUNA_URI = "/graphql"}
[[redirects]]
    from = "/graphql"
    to = "https://graphql.fauna.com/graphql"
    status = 200
    force = true
    headers = { Authorization = "Bearer HEADER_PLACEHOLDER" }